// Mock data for the entire application
export const mockUsers = [
  {
    id: 'user1',
    email: 'alice@example.com',
    displayName: 'Alice Johnson',
    photoURL: '👩‍🎨',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user2',
    email: 'bob@example.com',
    displayName: 'Bob Smith',
    photoURL: '🧹',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'user3',
    email: 'carol@example.com',
    displayName: 'Carol Wilson',
    photoURL: '👩‍🍳',
    createdAt: new Date('2024-03-20'),
  },
  {
    id: 'user4',
    email: 'david@example.com',
    displayName: 'David Brown',
    photoURL: '📸',
    createdAt: new Date('2024-04-05'),
  },
];

export const mockShops = [
  {
    id: 'shop1',
    ownerId: 'user1',
    ownerEmail: 'alice@example.com',
    ownerName: 'Alice Johnson',
    shopName: '🎨 Alice\'s Handmade Crafts',
    shopDescription: 'Premium handmade artwork and unique crafts. Every piece is a masterpiece created with passion, precision, and high-quality materials. From custom portraits to decorative items, we bring your vision to life.',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    category: 'Handmade Crafts & Artwork',
    phone: '+65 9123 4567',
    website: 'www.alicecrafts.com',
    instagram: '@alicecrafts',
    operatingHours: {
      monday: { open: '10:00', close: '18:00' },
      tuesday: { open: '10:00', close: '18:00' },
      wednesday: { open: '10:00', close: '18:00' },
      thursday: { open: '10:00', close: '18:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '12:00', close: '20:00' },
      sunday: { open: 'Closed', close: 'Closed' },
    },
    rating: 4.8,
    reviews: 142,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop2',
    ownerId: 'user3',
    ownerEmail: 'carol@example.com',
    ownerName: 'Carol Wilson',
    shopName: '🎂 Carol\'s Premium Bakery',
    shopDescription: 'Award-winning bakery specializing in custom cakes, pastries, and gourmet desserts. Fresh ingredients baked daily. Perfect for weddings, celebrations, and special occasions.',
    location: 'Singapore, East Coast',
    coordinates: { lat: 1.3043, lng: 103.9057 },
    category: 'Baked Goods & Desserts',
    phone: '+65 8765 4321',
    website: 'www.carolsbakery.com',
    instagram: '@carolsbakery',
    operatingHours: {
      monday: { open: '08:00', close: '19:00' },
      tuesday: { open: '08:00', close: '19:00' },
      wednesday: { open: '08:00', close: '19:00' },
      thursday: { open: '08:00', close: '19:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '09:00', close: '18:00' },
    },
    rating: 4.7,
    reviews: 168,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop3',
    ownerId: 'user4',
    ownerEmail: 'david@example.com',
    ownerName: 'David Brown',
    shopName: '📷 David\'s Professional Photography',
    shopDescription: 'Capturing moments that matter. Professional photography for weddings, events, portraits, and corporate sessions. High-end equipment and experienced photographers ensure stunning results.',
    location: 'Singapore, North District',
    coordinates: { lat: 1.4195, lng: 103.8453 },
    category: 'Photography & Videography Services',
    phone: '+65 9876 5432',
    website: 'www.davidphoto.com',
    instagram: '@davidphoto',
    operatingHours: {
      monday: { open: '09:00', close: '21:00' },
      tuesday: { open: '09:00', close: '21:00' },
      wednesday: { open: '09:00', close: '21:00' },
      thursday: { open: '09:00', close: '21:00' },
      friday: { open: '09:00', close: '22:00' },
      saturday: { open: '08:00', close: '22:00' },
      sunday: { open: '10:00', close: '20:00' },
    },
    rating: 4.9,
    reviews: 256,
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop4',
    ownerId: 'user5',
    ownerEmail: 'emma@example.com',
    ownerName: 'Emma Lee',
    shopName: '💅 Emma\'s Beauty & Wellness Studio',
    shopDescription: 'Premium beauty and wellness services including facials, massages, nail art, and skincare treatments. Relaxing ambiance with professional therapists. Book your pampering session today!',
    location: 'Singapore, Orchard',
    coordinates: { lat: 1.3038, lng: 103.8325 },
    category: 'Beauty & Personal Care',
    phone: '+65 8765 1234',
    website: 'www.emmabelty.com',
    instagram: '@emmabeauty',
    operatingHours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '11:00', close: '18:00' },
    },
    rating: 4.6,
    reviews: 189,
    createdAt: new Date('2024-05-12'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop5',
    ownerId: 'user6',
    ownerEmail: 'james@example.com',
    ownerName: 'James Chen',
    shopName: '🏋️ James\'s Fitness & Coaching',
    shopDescription: 'Personal training and fitness coaching for all levels. Customized workout plans, nutrition guidance, and online coaching. Transform your body and lifestyle with our expert trainers.',
    location: 'Singapore, West Coast',
    coordinates: { lat: 1.3431, lng: 103.7618 },
    category: 'Consulting & Coaching',
    phone: '+65 9111 2233',
    website: 'www.jamesfit.com',
    instagram: '@jamesfitnesssg',
    operatingHours: {
      monday: { open: '06:00', close: '22:00' },
      tuesday: { open: '06:00', close: '22:00' },
      wednesday: { open: '06:00', close: '22:00' },
      thursday: { open: '06:00', close: '22:00' },
      friday: { open: '06:00', close: '22:00' },
      saturday: { open: '08:00', close: '20:00' },
      sunday: { open: '08:00', close: '18:00' },
    },
    rating: 4.7,
    reviews: 203,
    createdAt: new Date('2024-06-08'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop6',
    ownerId: 'user7',
    ownerEmail: 'sarah@example.com',
    ownerName: 'Sarah Patel',
    shopName: '📚 Sarah\'s Content & Writing Services',
    shopDescription: 'Professional copywriting, blog content, social media management, and SEO-optimized articles. We create engaging content that converts and ranks. Perfect for startups and established brands.',
    location: 'Singapore, CBD',
    coordinates: { lat: 1.2768, lng: 103.8472 },
    category: 'Writing & Content Services',
    phone: '+65 8888 9999',
    website: 'www.sarahcontent.com',
    instagram: '@sarahcontentsg',
    operatingHours: {
      monday: { open: '09:00', close: '18:00' },
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: 'Closed', close: 'Closed' },
      sunday: { open: 'Closed', close: 'Closed' },
    },
    rating: 4.5,
    reviews: 127,
    createdAt: new Date('2024-07-22'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop7',
    ownerId: 'user8',
    ownerEmail: 'michael@example.com',
    ownerName: 'Michael Wong',
    shopName: '🌿 Michael\'s Organic & Wellness',
    shopDescription: 'Specializing in organic wellness products, herbal supplements, and natural health solutions. All products are certified organic and sourced ethically. Your health is our priority!',
    location: 'Singapore, Bishan',
    coordinates: { lat: 1.3521, lng: 103.8451 },
    category: 'Health & Wellness',
    phone: '+65 9555 6666',
    website: 'www.michaelwellness.com',
    instagram: '@michaelorganic',
    operatingHours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '09:00', close: '19:00' },
      sunday: { open: '11:00', close: '17:00' },
    },
    rating: 4.8,
    reviews: 214,
    createdAt: new Date('2024-08-10'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop8',
    ownerId: 'user9',
    ownerEmail: 'lisa@example.com',
    ownerName: 'Lisa Kumar',
    shopName: '🏠 Lisa\'s Home Decor & Furniture',
    shopDescription: 'Modern and contemporary home furnishings, decor items, and furniture solutions. Transform your space into a beautiful home. Custom orders welcome with fast delivery options.',
    location: 'Singapore, Clementi',
    coordinates: { lat: 1.3344, lng: 103.7618 },
    category: 'Home Decor & Furniture',
    phone: '+65 8444 7777',
    website: 'www.lisahome.com',
    instagram: '@lisahomedecorig',
    operatingHours: {
      monday: { open: '11:00', close: '20:00' },
      tuesday: { open: '11:00', close: '20:00' },
      wednesday: { open: '11:00', close: '20:00' },
      thursday: { open: '11:00', close: '20:00' },
      friday: { open: '11:00', close: '21:00' },
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '10:00', close: '19:00' },
    },
    rating: 4.4,
    reviews: 156,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop9',
    ownerId: 'user10',
    ownerEmail: 'rachel@example.com',
    ownerName: 'Rachel Tan',
    shopName: '💄 Rachel\'s Makeup Artistry Studio',
    shopDescription: 'Professional makeup artistry for weddings, events, and special occasions. Bridal makeup specialist with luxury products. Trial sessions available. Transform your look for any event.',
    location: 'Singapore, Jurong',
    coordinates: { lat: 1.3387, lng: 103.7467 },
    category: 'Beauty & Personal Care',
    phone: '+65 9222 3344',
    website: 'www.rachelmakeup.com',
    instagram: '@rachelmakeupsg',
    operatingHours: {
      monday: { open: '10:00', close: '20:00' },
      tuesday: { open: '10:00', close: '20:00' },
      wednesday: { open: '10:00', close: '20:00' },
      thursday: { open: '10:00', close: '20:00' },
      friday: { open: '10:00', close: '21:00' },
      saturday: { open: '09:00', close: '21:00' },
      sunday: { open: '10:00', close: '19:00' },
    },
    rating: 4.8,
    reviews: 198,
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop10',
    ownerId: 'user11',
    ownerEmail: 'kevin@example.com',
    ownerName: 'Kevin Lim',
    shopName: '🎵 Kevin\'s Music Lessons & Production',
    shopDescription: 'Professional music lessons for guitar, piano, and vocal training. Music production and recording services. Online and in-studio sessions available. All skill levels welcome.',
    location: 'Singapore, Ang Mo Kio',
    coordinates: { lat: 1.3695, lng: 103.8449 },
    category: 'Music & Arts Education',
    phone: '+65 8333 4455',
    website: 'www.kevinmusic.com',
    instagram: '@kevinmusicsg',
    operatingHours: {
      monday: { open: '09:00', close: '21:00' },
      tuesday: { open: '09:00', close: '21:00' },
      wednesday: { open: '09:00', close: '21:00' },
      thursday: { open: '09:00', close: '21:00' },
      friday: { open: '09:00', close: '22:00' },
      saturday: { open: '10:00', close: '22:00' },
      sunday: { open: '10:00', close: '20:00' },
    },
    rating: 4.7,
    reviews: 145,
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop11',
    ownerId: 'user12',
    ownerEmail: 'nina@example.com',
    ownerName: 'Nina Sharma',
    shopName: '🧘 Nina\'s Yoga & Meditation Center',
    shopDescription: 'Holistic yoga and meditation classes for stress relief, fitness, and mindfulness. Expert instructors with years of experience. Classes for all levels and ages. Start your wellness journey today.',
    location: 'Singapore, Tampines',
    coordinates: { lat: 1.3521, lng: 103.9368 },
    category: 'Health & Wellness',
    phone: '+65 9444 5566',
    website: 'www.ninayoga.com',
    instagram: '@ninayogasg',
    operatingHours: {
      monday: { open: '06:00', close: '20:00' },
      tuesday: { open: '06:00', close: '20:00' },
      wednesday: { open: '06:00', close: '20:00' },
      thursday: { open: '06:00', close: '20:00' },
      friday: { open: '06:00', close: '20:00' },
      saturday: { open: '08:00', close: '18:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    rating: 4.9,
    reviews: 267,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop12',
    ownerId: 'user13',
    ownerEmail: 'ryan@example.com',
    ownerName: 'Ryan Koh',
    shopName: '📱 Ryan\'s Tech & IT Consulting',
    shopDescription: 'Professional tech consulting for businesses and startups. Web development, app design, digital transformation, and IT solutions. Expert team with 10+ years experience. Transform your digital presence.',
    location: 'Singapore, Marina Bay',
    coordinates: { lat: 1.2768, lng: 103.8472 },
    category: 'Consulting & Coaching',
    phone: '+65 8555 6677',
    website: 'www.ryantech.com',
    instagram: '@ryantech_sg',
    operatingHours: {
      monday: { open: '09:00', close: '19:00' },
      tuesday: { open: '09:00', close: '19:00' },
      wednesday: { open: '09:00', close: '19:00' },
      thursday: { open: '09:00', close: '19:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: 'Closed', close: 'Closed' },
      sunday: { open: 'Closed', close: 'Closed' },
    },
    rating: 4.8,
    reviews: 189,
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop13',
    ownerId: 'user14',
    ownerEmail: 'jessica@example.com',
    ownerName: 'Jessica Wong',
    shopName: '👗 Jessica\'s Fashion & Styling',
    shopDescription: 'Personalized fashion styling and wardrobe consultation. Custom tailoring services for suits, dresses, and traditional wear. Personal shopping assistance. Elevate your personal style.',
    location: 'Singapore, Novena',
    coordinates: { lat: 1.3809, lng: 103.8461 },
    category: 'Fashion & Apparel',
    phone: '+65 8666 7788',
    website: 'www.jessicafashion.com',
    instagram: '@jessicastyling',
    operatingHours: {
      monday: { open: '11:00', close: '20:00' },
      tuesday: { open: '11:00', close: '20:00' },
      wednesday: { open: '11:00', close: '20:00' },
      thursday: { open: '11:00', close: '20:00' },
      friday: { open: '11:00', close: '21:00' },
      saturday: { open: '10:00', close: '21:00' },
      sunday: { open: '10:00', close: '19:00' },
    },
    rating: 4.6,
    reviews: 172,
    createdAt: new Date('2024-07-05'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop14',
    ownerId: 'user15',
    ownerEmail: 'arun@example.com',
    ownerName: 'Arun Nair',
    shopName: '🍽️ Arun\'s Catering & Event Planning',
    shopDescription: 'Full-service catering for corporate events, weddings, and parties. Customized menus featuring fusion cuisine and authentic flavors. Professional event coordination included. Make your event memorable.',
    location: 'Singapore, Geylang',
    coordinates: { lat: 1.3131, lng: 103.8624 },
    category: 'Food & Beverage Services',
    phone: '+65 9777 8899',
    website: 'www.arunncatering.com',
    instagram: '@aruncatering',
    operatingHours: {
      monday: { open: '10:00', close: '22:00' },
      tuesday: { open: '10:00', close: '22:00' },
      wednesday: { open: '10:00', close: '22:00' },
      thursday: { open: '10:00', close: '22:00' },
      friday: { open: '10:00', close: '23:00' },
      saturday: { open: '10:00', close: '23:00' },
      sunday: { open: '11:00', close: '21:00' },
    },
    rating: 4.7,
    reviews: 231,
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop15',
    ownerId: 'user16',
    ownerEmail: 'sophia@example.com',
    ownerName: 'Sophia Lee',
    shopName: '📖 Sophia\'s Tutoring & Academic Services',
    shopDescription: 'Personalized tutoring for primary, secondary, and JC levels. Expert in Mathematics, Sciences, and English. Small group classes and one-on-one sessions. Improve grades and build confidence.',
    location: 'Singapore, Bukit Timah',
    coordinates: { lat: 1.3481, lng: 103.7744 },
    category: 'Education & Tutoring',
    phone: '+65 8888 1122',
    website: 'www.sophiatutoring.com',
    instagram: '@sophiatutoringsg',
    operatingHours: {
      monday: { open: '09:00', close: '20:00' },
      tuesday: { open: '09:00', close: '20:00' },
      wednesday: { open: '09:00', close: '20:00' },
      thursday: { open: '09:00', close: '20:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '10:00', close: '17:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    rating: 4.9,
    reviews: 245,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop16',
    ownerId: 'user17',
    ownerEmail: 'daniel@example.com',
    ownerName: 'Daniel Chua',
    shopName: '🐕 Daniel\'s Pet Grooming & Care',
    shopDescription: 'Professional pet grooming for dogs and cats. Spa treatments, nail trimming, and behavioral training. Pet-friendly environment with experienced handlers. Keep your pets happy and healthy.',
    location: 'Singapore, Bedok',
    coordinates: { lat: 1.3244, lng: 103.9286 },
    category: 'Pet Services & Supplies',
    phone: '+65 9999 2233',
    website: 'www.danielpets.com',
    instagram: '@danielpetcare',
    operatingHours: {
      monday: { open: '10:00', close: '19:00' },
      tuesday: { open: '10:00', close: '19:00' },
      wednesday: { open: '10:00', close: '19:00' },
      thursday: { open: '10:00', close: '19:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '09:00', close: '18:00' },
    },
    rating: 4.8,
    reviews: 203,
    createdAt: new Date('2024-05-22'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop17',
    ownerId: 'user18',
    ownerEmail: 'marcus@example.com',
    ownerName: 'Marcus Ng',
    shopName: '🚗 Marcus\'s Auto Care & Detailing',
    shopDescription: 'Professional vehicle detailing and maintenance. Car wash, waxing, interior cleaning, and engine care. Expert technicians with premium products. Keep your car looking showroom new.',
    location: 'Singapore, Buona Vista',
    coordinates: { lat: 1.3064, lng: 103.7896 },
    category: 'Automotive Services',
    phone: '+65 8111 3344',
    website: 'www.marcusauto.com',
    instagram: '@marcusautocare',
    operatingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: { open: 'Closed', close: 'Closed' },
    },
    rating: 4.7,
    reviews: 167,
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop18',
    ownerId: 'user19',
    ownerEmail: 'Elena@example.com',
    ownerName: 'Elena Cruz',
    shopName: '💐 Elena\'s Flower Design & Events',
    shopDescription: 'Custom floral arrangements for weddings, events, and corporate occasions. Fresh imported flowers daily. Wedding florals specialist. Create beautiful moments with stunning arrangements.',
    location: 'Singapore, Tanjong Pagar',
    coordinates: { lat: 1.2744, lng: 103.8425 },
    category: 'Event & Decor Services',
    phone: '+65 9333 4455',
    website: 'www.elenaflowers.com',
    instagram: '@elenaflowerdesign',
    operatingHours: {
      monday: { open: '09:00', close: '20:00' },
      tuesday: { open: '09:00', close: '20:00' },
      wednesday: { open: '09:00', close: '20:00' },
      thursday: { open: '09:00', close: '20:00' },
      friday: { open: '09:00', close: '21:00' },
      saturday: { open: '09:00', close: '21:00' },
      sunday: { open: '10:00', close: '18:00' },
    },
    rating: 4.8,
    reviews: 186,
    createdAt: new Date('2024-08-20'),
    updatedAt: new Date('2024-10-15'),
  },
];

export const mockListings = [
  // Alice's shop products
  {
    id: 'listing1',
    name: 'Hand-painted Canvas Art - Sunset Dreams',
    description: 'Stunning hand-painted canvas artwork featuring a vibrant sunset over mountains. Size 60x80cm, ready to hang. Premium acrylic paints on high-quality canvas. Adds warmth and sophistication to any room.',
    category: 'Handmade Crafts & Artwork',
    price: 85,
    period: 'unit',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['/images/canvas-art.svg'],
    type: 'product' as const,
    stock: 5,
    shopId: 'shop1',
    isActive: true,
    rating: 4.9,
    reviews: 47,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: 'listing2',
    name: 'Custom Handcrafted Wooden Furniture Set',
    description: 'Bespoke wooden furniture made from premium hardwood. Each piece is hand-selected and custom-built to your specifications. Includes dining table, chairs, and storage. Perfect for modern and traditional interiors.',
    category: 'Home Decor & Furniture',
    price: 450,
    period: 'unit',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['/images/wooden-furniture.svg'],
    type: 'product' as const,
    stock: 2,
    shopId: 'shop1',
    isActive: true,
    rating: 4.8,
    reviews: 31,
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-10-12'),
  },
  {
    id: 'listing_alice_1',
    name: 'Watercolor Painting Masterclass - 6 Weeks',
    description: 'Comprehensive 6-week online course on watercolor techniques. Learn from beginner to advanced levels. Includes personalized feedback, materials guide, and lifetime access to course materials. Perfect for all skill levels.',
    category: 'Handmade Crafts & Artwork',
    price: 180,
    period: 'session',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['🎨'],
    type: 'service' as const,
    shopId: 'shop1',
    isActive: true,
    rating: 4.8,
    reviews: 63,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-10-08'),
  },
  {
    id: 'listing_alice_2',
    name: 'Custom Portrait Commission - Full Family',
    description: 'Personalized hand-painted portrait of your family, friends, or pets. High-quality materials and professional artistry. Includes consultation and revisions. Frame-ready. Perfect gift or home decoration.',
    category: 'Handmade Crafts & Artwork',
    price: 300,
    period: 'unit',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['/images/portrait.svg'],
    type: 'product' as const,
    stock: 2,
    shopId: 'shop1',
    isActive: true,
    rating: 4.9,
    reviews: 89,
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-10-14'),
  },
  {
    id: 'listing_alice_3',
    name: 'Professional Interior Design Consultation',
    description: 'Expert consultation for home or office interior design. Includes space planning, color schemes, furniture selection, and mood boards. 2-hour session with follow-up recommendations. Transform your space beautifully.',
    category: 'Handmade Crafts & Artwork',
    price: 150,
    period: 'session',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['🏠'],
    type: 'service' as const,
    shopId: 'shop1',
    isActive: true,
    rating: 4.8,
    reviews: 52,
    createdAt: new Date('2024-07-20'),
    updatedAt: new Date('2024-10-12'),
  },
  {
    id: 'listing_alice_4',
    name: 'Artisan Ceramic Vases Collection - Set of 3',
    description: 'Handcrafted ceramic vases with unique glazes and textures. Each vase is one-of-a-kind, featuring beautiful earth tones and modern designs. Perfect for fresh flowers or standalone decorations.',
    category: 'Handmade Crafts & Artwork',
    price: 120,
    period: 'unit',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['/images/ceramic-vases.svg'],
    type: 'product' as const,
    stock: 12,
    shopId: 'shop1',
    isActive: true,
    rating: 4.7,
    reviews: 34,
    createdAt: new Date('2024-08-05'),
    updatedAt: new Date('2024-10-10'),
  },
  // Carol's shop products
  {
    id: 'listing3',
    name: 'Premium Chocolate Layer Cake',
    description: 'Decadent multi-layer chocolate cake with rich ganache and ganache-filled layers. Serves 12-16 people. Available with custom decorations. 48 hours advance notice required. Perfect for celebrations.',
    category: 'Baked Goods & Desserts',
    price: 65,
    period: 'unit',
    location: 'Singapore, East Coast',
    coordinates: { lat: 1.3043, lng: 103.9057 },
    owner: 'Carol Wilson',
    ownerContact: 'carol@example.com',
    imageUrls: ['/images/chocolate-cake.svg'],
    type: 'product' as const,
    stock: 15,
    shopId: 'shop2',
    isActive: true,
    rating: 4.9,
    reviews: 78,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-10-14'),
  },
  {
    id: 'listing_carol_1',
    name: 'Artisan Sourdough Bread Collection',
    description: 'Fresh daily-baked sourdough breads with organic flour and natural fermentation. Available in classic, whole wheat, and seeded varieties. Warm, crusty exterior with soft, tangy interior.',
    category: 'Baked Goods & Desserts',
    price: 8,
    period: 'unit',
    location: 'Singapore, East Coast',
    coordinates: { lat: 1.3043, lng: 103.9057 },
    owner: 'Carol Wilson',
    ownerContact: 'carol@example.com',
    imageUrls: ['/images/sourdough-bread.svg'],
    type: 'product' as const,
    stock: 30,
    shopId: 'shop2',
    isActive: true,
    rating: 4.8,
    reviews: 125,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-10-14'),
  },
  {
    id: 'listing_carol_2',
    name: 'French Macaron Assortment Box',
    description: 'Colorful assorted French macarons with flavors like pistachio, raspberry, chocolate, and matcha. Each box contains 12 premium macarons. Perfect for gifts or special treats. Gourmet quality.',
    category: 'Baked Goods & Desserts',
    price: 35,
    period: 'unit',
    location: 'Singapore, East Coast',
    coordinates: { lat: 1.3043, lng: 103.9057 },
    owner: 'Carol Wilson',
    ownerContact: 'carol@example.com',
    imageUrls: ['/images/macaron-box.svg'],
    type: 'product' as const,
    stock: 20,
    shopId: 'shop2',
    isActive: true,
    rating: 4.9,
    reviews: 92,
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-10-13'),
  },
  {
    id: 'listing_carol_3',
    name: 'Wedding & Event Cake Design Service',
    description: 'Custom wedding and celebration cakes. Multi-tiered designs with premium decorations, personalized details, and gourmet flavors. Consultation included. Delivery available. Start-to-finish coordination.',
    category: 'Baked Goods & Desserts',
    price: 250,
    period: 'session',
    location: 'Singapore, East Coast',
    coordinates: { lat: 1.3043, lng: 103.9057 },
    owner: 'Carol Wilson',
    ownerContact: 'carol@example.com',
    imageUrls: ['💍'],
    type: 'service' as const,
    shopId: 'shop2',
    isActive: true,
    rating: 4.9,
    reviews: 68,
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-10-12'),
  },
  // David's shop services
  {
    id: 'listing4',
    name: 'Premium Wedding Photography Package',
    description: 'Full-day wedding coverage with 2 professional photographers. Includes 1000+ professionally edited photos, drone photography, same-day video highlights, and a luxury photo album.',
    category: 'Photography & Videography Services',
    price: 2500,
    period: 'session',
    location: 'Singapore, North District',
    coordinates: { lat: 1.4195, lng: 103.8453 },
    owner: 'David Brown',
    ownerContact: 'david@example.com',
    imageUrls: ['/images/camera.svg'],
    type: 'service' as const,
    stock: undefined,
    shopId: 'shop3',
    isActive: true,
    rating: 4.9,
    reviews: 134,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-10-13'),
  },
  {
    id: 'listing_david_1',
    name: 'Professional Portrait Session',
    description: 'Studio or outdoor portrait session for individuals, couples, or families. Includes 1 hour session, professional styling advice, 50+ edited photos, and digital gallery access.',
    category: 'Photography & Videography Services',
    price: 350,
    period: 'session',
    location: 'Singapore, North District',
    coordinates: { lat: 1.4195, lng: 103.8453 },
    owner: 'David Brown',
    ownerContact: 'david@example.com',
    imageUrls: ['/images/portrait.svg'],
    type: 'service' as const,
    shopId: 'shop3',
    isActive: true,
    rating: 4.8,
    reviews: 89,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-10-12'),
  },
  {
    id: 'listing_david_2',
    name: 'Corporate Event Photography',
    description: 'Professional photography for corporate events, conferences, and business functions. 6-8 hour coverage, candid and posed shots, quick turnaround on edited photos.',
    category: 'Photography & Videography Services',
    price: 800,
    period: 'session',
    location: 'Singapore, North District',
    coordinates: { lat: 1.4195, lng: 103.8453 },
    owner: 'David Brown',
    ownerContact: 'david@example.com',
    imageUrls: ['🏢'],
    type: 'service' as const,
    shopId: 'shop3',
    isActive: true,
    rating: 4.7,
    reviews: 56,
    createdAt: new Date('2024-05-12'),
    updatedAt: new Date('2024-10-11'),
  },
  {
    id: 'listing_david_3',
    name: 'Professional Headshot Photography',
    description: 'Executive and professional headshots for LinkedIn, corporate websites, and marketing materials. Includes multiple looks, backgrounds, and outfit changes. Digital gallery with unlimited downloads.',
    category: 'Photography & Videography Services',
    price: 200,
    period: 'session',
    location: 'Singapore, North District',
    coordinates: { lat: 1.4195, lng: 103.8453 },
    owner: 'David Brown',
    ownerContact: 'david@example.com',
    imageUrls: ['💼'],
    type: 'service' as const,
    shopId: 'shop3',
    isActive: true,
    rating: 4.9,
    reviews: 102,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: 'listing5',
    name: 'Home Cleaning Service',
    description: 'Professional home cleaning for 3-bedroom apartments',
    category: 'Cleaning & Organization Services',
    price: 120,
    period: 'day',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Bob Smith',
    ownerContact: 'bob@example.com',
    imageUrls: ['🧹'],
    type: 'service' as const,
    stock: undefined,
    shopId: undefined,
    isActive: true,
    rating: 4.6,
    reviews: 28,
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-10-11'),
  },
];

export const mockRentals = [
  // More realistic rental orders to populate analytics
  {
    id: 'rental1',
    toolId: 'listing1',
    toolName: 'Hand-painted Canvas Art - Sunset Dreams',
    renterName: 'John Doe',
    renterEmail: 'john@example.com',
    ownerEmail: 'alice@example.com',
    ownerName: 'Alice Johnson',
    shopId: 'shop1',
    startDate: '2024-10-20',
    endDate: undefined,
    startTime: '10:00',
    endTime: undefined,
    message: 'Love this artwork! Perfect for my living room.',
    quantity: 1,
    totalCost: 85,
    status: 'completed' as const,
    orderType: 'product' as const,
    location: 'Singapore, Central District',
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-18'),
  },
  {
    id: 'rental2',
    toolId: 'listing4',
    toolName: 'Premium Wedding Photography Package',
    renterName: 'Sarah Chen',
    renterEmail: 'sarah@example.com',
    ownerEmail: 'david@example.com',
    ownerName: 'David Brown',
    shopId: 'shop3',
    startDate: '2024-11-15',
    endDate: '2024-11-15',
    startTime: '10:00',
    endTime: '18:00',
    message: 'Wedding photography for our special day! So excited!',
    quantity: undefined,
    totalCost: 2500,
    status: 'completed' as const,
    orderType: 'service' as const,
    location: 'Singapore, North District',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: 'rental3',
    toolId: 'listing3',
    toolName: 'Premium Chocolate Layer Cake',
    renterName: 'Emma Wilson',
    renterEmail: 'emma@example.com',
    ownerEmail: 'carol@example.com',
    ownerName: 'Carol Wilson',
    shopId: 'shop2',
    startDate: '2024-10-22',
    endDate: undefined,
    startTime: '14:00',
    endTime: undefined,
    message: 'Birthday cake for my daughter. Please make it special!',
    quantity: 1,
    totalCost: 65,
    status: 'completed' as const,
    orderType: 'product' as const,
    location: 'Singapore, East Coast',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-22'),
  },
  {
    id: 'rental4',
    toolId: 'listing_alice_2',
    toolName: 'Custom Portrait Commission - Full Family',
    renterName: 'Michael Johnson',
    renterEmail: 'michael@example.com',
    ownerEmail: 'alice@example.com',
    ownerName: 'Alice Johnson',
    shopId: 'shop1',
    startDate: '2024-09-15',
    endDate: undefined,
    startTime: '10:00',
    endTime: undefined,
    message: 'Family portrait for our home',
    quantity: 1,
    totalCost: 300,
    status: 'completed' as const,
    orderType: 'product' as const,
    location: 'Singapore, Central District',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-10-05'),
  },
  {
    id: 'rental5',
    toolId: 'listing_david_1',
    toolName: 'Professional Portrait Session',
    renterName: 'Lisa Wong',
    renterEmail: 'lisa@example.com',
    ownerEmail: 'david@example.com',
    ownerName: 'David Brown',
    shopId: 'shop3',
    startDate: '2024-10-25',
    endDate: '2024-10-25',
    startTime: '14:00',
    endTime: '15:00',
    message: 'LinkedIn headshot session',
    quantity: undefined,
    totalCost: 350,
    status: 'completed' as const,
    orderType: 'service' as const,
    location: 'Singapore, North District',
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-10-25'),
  },
  {
    id: 'rental6',
    toolId: 'listing_carol_1',
    toolName: 'Artisan Sourdough Bread Collection',
    renterName: 'James Park',
    renterEmail: 'james@example.com',
    ownerEmail: 'carol@example.com',
    ownerName: 'Carol Wilson',
    shopId: 'shop2',
    startDate: '2024-10-26',
    endDate: undefined,
    startTime: '09:00',
    endTime: undefined,
    message: 'Weekly bread delivery',
    quantity: 3,
    totalCost: 24,
    status: 'completed' as const,
    orderType: 'product' as const,
    location: 'Singapore, East Coast',
    createdAt: new Date('2024-10-26'),
    updatedAt: new Date('2024-10-26'),
  },
  {
    id: 'rental7',
    toolId: 'listing_alice_1',
    toolName: 'Watercolor Painting Masterclass - 6 Weeks',
    renterName: 'Sophie Lee',
    renterEmail: 'sophie@example.com',
    ownerEmail: 'alice@example.com',
    ownerName: 'Alice Johnson',
    shopId: 'shop1',
    startDate: '2024-09-01',
    endDate: '2024-10-15',
    startTime: '18:00',
    endTime: '19:30',
    message: 'Enrolled in watercolor class',
    quantity: undefined,
    totalCost: 180,
    status: 'completed' as const,
    orderType: 'service' as const,
    location: 'Singapore, Central District',
    createdAt: new Date('2024-08-28'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'rental8',
    toolId: 'listing_carol_2',
    toolName: 'French Macaron Assortment Box',
    renterName: 'Maria Garcia',
    renterEmail: 'maria@example.com',
    ownerEmail: 'carol@example.com',
    ownerName: 'Carol Wilson',
    shopId: 'shop2',
    startDate: '2024-10-23',
    endDate: undefined,
    startTime: '16:00',
    endTime: undefined,
    message: 'Gift box for my friend',
    quantity: 2,
    totalCost: 70,
    status: 'completed' as const,
    orderType: 'product' as const,
    location: 'Singapore, East Coast',
    createdAt: new Date('2024-10-22'),
    updatedAt: new Date('2024-10-23'),
  },
  {
    id: 'rental9',
    toolId: 'listing_david_2',
    toolName: 'Corporate Event Photography',
    renterName: 'Tech Corp Events',
    renterEmail: 'events@techcorp.com',
    ownerEmail: 'david@example.com',
    ownerName: 'David Brown',
    shopId: 'shop3',
    startDate: '2024-10-18',
    endDate: '2024-10-18',
    startTime: '10:00',
    endTime: '18:00',
    message: 'Conference coverage needed',
    quantity: undefined,
    totalCost: 800,
    status: 'completed' as const,
    orderType: 'service' as const,
    location: 'Singapore, North District',
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-10-18'),
  },
  {
    id: 'rental10',
    toolId: 'listing_alice_4',
    toolName: 'Artisan Ceramic Vases Collection - Set of 3',
    renterName: 'Robert Chen',
    renterEmail: 'robert@example.com',
    ownerEmail: 'alice@example.com',
    ownerName: 'Alice Johnson',
    shopId: 'shop1',
    startDate: '2024-10-24',
    endDate: undefined,
    startTime: '11:00',
    endTime: undefined,
    message: 'Beautiful vases for my home',
    quantity: 1,
    totalCost: 120,
    status: 'completed' as const,
    orderType: 'product' as const,
    location: 'Singapore, Central District',
    createdAt: new Date('2024-10-23'),
    updatedAt: new Date('2024-10-24'),
  },
];

export const mockReviews = [
  {
    id: 'review1',
    listingId: 'listing1',
    reviewerName: 'John Doe',
    reviewerEmail: 'john@example.com',
    rating: 5,
    comment: 'Absolutely stunning artwork! The colors are vibrant and the quality is exceptional. Highly recommend!',
    createdAt: new Date('2024-09-20'),
  },
  {
    id: 'review2',
    listingId: 'listing3',
    reviewerName: 'Emma Wilson',
    reviewerEmail: 'emma@example.com',
    rating: 5,
    comment: 'The cake was delicious and beautifully decorated. Carol\'s bakery never disappoints!',
    createdAt: new Date('2024-09-15'),
  },
  {
    id: 'review3',
    listingId: 'listing4',
    reviewerName: 'Sarah Chen',
    reviewerEmail: 'sarah@example.com',
    rating: 5,
    comment: 'David captured our wedding perfectly! Professional, creative, and amazing results.',
    createdAt: new Date('2024-09-10'),
  },
  {
    id: 'review4',
    listingId: 'listing_alice_2',
    reviewerName: 'Michael Johnson',
    reviewerEmail: 'michael@example.com',
    rating: 5,
    comment: 'Our family portrait turned out beautifully. Alice is incredibly talented!',
    createdAt: new Date('2024-10-10'),
  },
  {
    id: 'review5',
    listingId: 'listing_carol_1',
    reviewerName: 'James Park',
    reviewerEmail: 'james@example.com',
    rating: 5,
    comment: 'Best sourdough bread in Singapore. Fresh and delicious every time!',
    createdAt: new Date('2024-10-15'),
  },
];

export const mockFavorites = [
  {
    id: 'fav1',
    userId: 'user_current',
    listingId: 'listing1',
    createdAt: new Date('2024-10-01'),
  },
  {
    id: 'fav2',
    userId: 'user_current',
    listingId: 'listing4',
    createdAt: new Date('2024-10-05'),
  },
];

export const mockChats = [
  {
    id: 'chat1',
    participants: ['user_current', 'user1'],
    lastMessage: 'That sounds great! When can you start?',
    lastMessageTime: new Date('2024-10-15'),
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-15'),
    messages: [
      {
        id: 'msg1',
        senderId: 'user1',
        text: 'Hi! I\'m interested in your services. Can you help with my project?',
        createdAt: new Date('2024-10-10'),
        read: true,
      },
      {
        id: 'msg2',
        senderId: 'user_current',
        text: 'Hi Alice! Yes, I\'d be happy to help. Tell me more about your project.',
        createdAt: new Date('2024-10-10'),
        read: true,
      },
      {
        id: 'msg3',
        senderId: 'user1',
        text: 'I need a custom wooden table for my living room',
        createdAt: new Date('2024-10-11'),
        read: true,
      },
      {
        id: 'msg4',
        senderId: 'user_current',
        text: 'That sounds great! When can you start?',
        createdAt: new Date('2024-10-15'),
        read: false,
      },
    ],
  },
];
