// Mock data for the entire application
export const mockUsers = [
  {
    id: 'user1',
    email: 'alice@example.com',
    displayName: 'Alice Johnson',
    photoURL: '👩‍💼',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'user2',
    email: 'bob@example.com',
    displayName: 'Bob Smith',
    photoURL: '👨‍💼',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'user3',
    email: 'carol@example.com',
    displayName: 'Carol Wilson',
    photoURL: '👩‍🍳',
    createdAt: new Date('2024-03-20'),
  },
  {
    id: 'user4',
    email: 'david@example.com',
    displayName: 'David Brown',
    photoURL: '📸',
    createdAt: new Date('2024-04-05'),
  },
];

export const mockShops = [
  {
    id: 'shop1',
    ownerId: 'user1',
    ownerEmail: 'alice@example.com',
    ownerName: 'Alice Johnson',
    shopName: 'Alice\'s Handmade Crafts',
    shopDescription: 'Beautiful handmade artwork and crafts made with love',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    category: 'Handmade Crafts & Artwork',
    phone: '+65 9123 4567',
    website: 'www.alicecrafts.com',
    instagram: '@alicecrafts',
    operatingHours: {
      monday: { open: '10:00', close: '18:00' },
      tuesday: { open: '10:00', close: '18:00' },
      wednesday: { open: '10:00', close: '18:00' },
      thursday: { open: '10:00', close: '18:00' },
      friday: { open: '10:00', close: '20:00' },
      saturday: { open: '12:00', close: '20:00' },
      sunday: { open: 'Closed', close: 'Closed' },
    },
    rating: 4.8,
    reviews: 42,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop2',
    ownerId: 'user3',
    ownerEmail: 'carol@example.com',
    ownerName: 'Carol Wilson',
    shopName: 'Carol\'s Bakery',
    shopDescription: 'Freshly baked goods and delicious desserts',
    location: 'Singapore, East Coast',
    coordinates: { lat: 1.3043, lng: 103.9057 },
    category: 'Baked Goods & Desserts',
    phone: '+65 8765 4321',
    website: 'www.carolsbakery.com',
    instagram: '@carolsbakery',
    operatingHours: {
      monday: { open: '08:00', close: '19:00' },
      tuesday: { open: '08:00', close: '19:00' },
      wednesday: { open: '08:00', close: '19:00' },
      thursday: { open: '08:00', close: '19:00' },
      friday: { open: '08:00', close: '20:00' },
      saturday: { open: '09:00', close: '20:00' },
      sunday: { open: '09:00', close: '18:00' },
    },
    rating: 4.6,
    reviews: 38,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'shop3',
    ownerId: 'user4',
    ownerEmail: 'david@example.com',
    ownerName: 'David Brown',
    shopName: 'David\'s Photography',
    shopDescription: 'Professional photography services for all occasions',
    location: 'Singapore, North District',
    coordinates: { lat: 1.4195, lng: 103.8453 },
    category: 'Photography & Videography Services',
    phone: '+65 9876 5432',
    website: 'www.davidphoto.com',
    instagram: '@davidphoto',
    operatingHours: {
      monday: { open: '09:00', close: '21:00' },
      tuesday: { open: '09:00', close: '21:00' },
      wednesday: { open: '09:00', close: '21:00' },
      thursday: { open: '09:00', close: '21:00' },
      friday: { open: '09:00', close: '22:00' },
      saturday: { open: '08:00', close: '22:00' },
      sunday: { open: '10:00', close: '20:00' },
    },
    rating: 4.9,
    reviews: 56,
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-10-15'),
  },
];

export const mockListings = [
  {
    id: 'listing1',
    name: 'Hand-painted Canvas Art',
    description: 'Beautiful hand-painted canvas artwork, 60x80cm, ready to hang',
    category: 'Handmade Crafts & Artwork',
    price: 85,
    period: 'unit',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['🎨'],
    type: 'product' as const,
    stock: 5,
    shopId: 'shop1',
    isActive: true,
    rating: 4.9,
    reviews: 23,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: 'listing2',
    name: 'Custom Wooden Furniture',
    description: 'Custom-made wooden furniture pieces to order',
    category: 'Home Decor & Furniture',
    price: 250,
    period: 'unit',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Alice Johnson',
    ownerContact: 'alice@example.com',
    imageUrls: ['🪑'],
    type: 'product' as const,
    stock: 3,
    shopId: 'shop1',
    isActive: true,
    rating: 4.7,
    reviews: 15,
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-10-12'),
  },
  {
    id: 'listing3',
    name: 'Chocolate Cake Order',
    description: 'Custom chocolate cake, serves 12 people, 48 hours notice required',
    category: 'Baked Goods & Desserts',
    price: 45,
    period: 'unit',
    location: 'Singapore, East Coast',
    coordinates: { lat: 1.3043, lng: 103.9057 },
    owner: 'Carol Wilson',
    ownerContact: 'carol@example.com',
    imageUrls: ['🎂'],
    type: 'product' as const,
    stock: 10,
    shopId: 'shop2',
    isActive: true,
    rating: 4.8,
    reviews: 34,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-10-14'),
  },
  {
    id: 'listing4',
    name: 'Wedding Photography Package',
    description: '8 hours coverage, 1000+ edited photos, includes drone shots',
    category: 'Photography & Videography Services',
    price: 1500,
    period: 'session',
    location: 'Singapore, North District',
    coordinates: { lat: 1.4195, lng: 103.8453 },
    owner: 'David Brown',
    ownerContact: 'david@example.com',
    imageUrls: ['📷'],
    type: 'service' as const,
    stock: undefined,
    shopId: 'shop3',
    isActive: true,
    rating: 4.9,
    reviews: 45,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-10-13'),
  },
  {
    id: 'listing5',
    name: 'Home Cleaning Service',
    description: 'Professional home cleaning for 3-bedroom apartments',
    category: 'Cleaning & Organization Services',
    price: 120,
    period: 'day',
    location: 'Singapore, Central District',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    owner: 'Bob Smith',
    ownerContact: 'bob@example.com',
    imageUrls: ['🧹'],
    type: 'service' as const,
    stock: undefined,
    shopId: undefined,
    isActive: true,
    rating: 4.6,
    reviews: 28,
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-10-11'),
  },
];

export const mockRentals = [
  {
    id: 'rental1',
    toolId: 'listing1',
    toolName: 'Hand-painted Canvas Art',
    renterName: 'John Doe',
    renterEmail: 'john@example.com',
    ownerEmail: 'alice@example.com',
    ownerName: 'Alice Johnson',
    shopId: 'shop1',
    startDate: '2024-10-20',
    endDate: undefined,
    startTime: '10:00',
    endTime: undefined,
    message: 'I would like to purchase this canvas art piece',
    quantity: 1,
    totalCost: 85,
    status: 'pending' as const,
    orderType: 'product' as const,
    location: 'Singapore, Central District',
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'rental2',
    toolId: 'listing4',
    toolName: 'Wedding Photography Package',
    renterName: 'Sarah Chen',
    renterEmail: 'sarah@example.com',
    ownerEmail: 'david@example.com',
    ownerName: 'David Brown',
    shopId: 'shop3',
    startDate: '2024-11-15',
    endDate: '2024-11-15',
    startTime: '10:00',
    endTime: '18:00',
    message: 'Wedding photography for our special day!',
    quantity: undefined,
    totalCost: 1500,
    status: 'approved' as const,
    orderType: 'service' as const,
    location: 'Singapore, North District',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-14'),
  },
];

export const mockReviews = [
  {
    id: 'review1',
    listingId: 'listing1',
    reviewerName: 'John Doe',
    reviewerEmail: 'john@example.com',
    rating: 5,
    comment: 'Beautiful artwork! Very satisfied with the quality.',
    createdAt: new Date('2024-09-20'),
  },
  {
    id: 'review2',
    listingId: 'listing3',
    reviewerName: 'Emma Watson',
    reviewerEmail: 'emma@example.com',
    rating: 5,
    comment: 'Amazing cake! Highly recommend Carol\'s bakery.',
    createdAt: new Date('2024-09-15'),
  },
  {
    id: 'review3',
    listingId: 'listing4',
    reviewerName: 'Michael Johnson',
    reviewerEmail: 'michael@example.com',
    rating: 5,
    comment: 'Professional photographer, excellent results!',
    createdAt: new Date('2024-09-10'),
  },
];

export const mockFavorites = [
  {
    id: 'fav1',
    userId: 'user_current',
    listingId: 'listing1',
    createdAt: new Date('2024-10-01'),
  },
  {
    id: 'fav2',
    userId: 'user_current',
    listingId: 'listing4',
    createdAt: new Date('2024-10-05'),
  },
];

export const mockChats = [
  {
    id: 'chat1',
    participants: ['user_current', 'user1'],
    lastMessage: 'That sounds great! When can you start?',
    lastMessageTime: new Date('2024-10-15'),
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-15'),
    messages: [
      {
        id: 'msg1',
        senderId: 'user1',
        text: 'Hi! I\'m interested in your services. Can you help with my project?',
        createdAt: new Date('2024-10-10'),
        read: true,
      },
      {
        id: 'msg2',
        senderId: 'user_current',
        text: 'Hi Alice! Yes, I\'d be happy to help. Tell me more about your project.',
        createdAt: new Date('2024-10-10'),
        read: true,
      },
      {
        id: 'msg3',
        senderId: 'user1',
        text: 'I need a custom wooden table for my living room',
        createdAt: new Date('2024-10-11'),
        read: true,
      },
      {
        id: 'msg4',
        senderId: 'user_current',
        text: 'That sounds great! When can you start?',
        createdAt: new Date('2024-10-15'),
        read: false,
      },
    ],
  },
];
